# and-sky-configured-maria.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: and-sky-configured-maria

data:
  create-my-bliss.sql: |-
    CREATE DATABASE IF NOT EXISTS simplydatabase;
    CREATE USER IF NOT EXISTS 'simplymaria'@'%' IDENTIFIED BY 'spillYourBeans';
    USE simplydatabase;
    GRANT ALL PRIVILEGES ON simplydatabase.* TO 'simplymaria'@'%';
    FLUSH PRIVILEGES;
    CREATE TABLE IF NOT EXISTS products (
        id mediumint(8) unsigned NOT NULL auto_increment, 
        Name varchar(255) default NULL, 
        Price varchar(255) default NULL, 
        ImageUrl varchar(255) default NULL, 
        PRIMARY KEY (id)
    ); 
    INSERT INTO products (Name, Price, ImageUrl) VALUES 
    ('Laptop','100','c-1.png'), 
    ('Drone','200','c-2.png'), 
    ('VR','300','c-3.png'), 
    ('Tablet','50','c-5.png'), 
    ('Watch','90','c-6.png'), 
    ('Phone Covers','20','c-7.png'), 
    ('Phone','80','c-8.png'), 
    ('Laptop','150','c-4.png');
