# secrets.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: little-secrets
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "retail-therapy-app"
    app.kubernetes.io/instance: "retail-therapy-app"
  annotations:
    meta.helm.sh/release-name: "retail-therapy-app"
    meta.helm.sh/release-namespace: "default"
type: Opaque
data:
  DB_PASSWORD: c3BpbGxZb3VyQmVhbnM=
  MYSQL_ROOT_PASSWORD: Z3Jvd1lvdXJSb290cw==