apiVersion: v1
kind: ConfigMap
metadata:
  name: and-sky-configured-toggle-and-probes
data:
  FEATURE_DARK_MODE: "true"
  # Replacing database password with secret
  alive-and-kicking.php: |
    <?php
    $dbHost = getenv('DB_HOST');
    $dbUser = getenv('DB_USER');
    $dbPassword = getenv('DB_PASSWORD'); 
    $dbName = getenv('DB_NAME');

    $link = mysqli_connect($dbHost, $dbUser, $dbPassword, $dbName);

    if ($link) {
        $res = mysqli_query($link, "SELECT * FROM products LIMIT 1;");
        if ($res) {
            http_response_code(200);
            echo "This app is healthy";
        } else {
            http_response_code(500);
            echo "This app is under the weather: unable to query the database";
        }
    } else {
        http_response_code(500);
        echo "This app is under the weather: unable to connect to the database";
    }
    ?>