apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-pod-for-maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simply-maria
  template:
    metadata:
      labels:
        app: simply-maria
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.2.20
        ports:
        - containerPort: 3306        
        env:
        - name: DB_HOST
          value: at-your-service
        - name: MYSQL_ROOT_PASSWORD
          value: growYourRoots
        - name: DB_PASSWORD
          value: spillYourBeans

        volumeMounts:
        - name: and-sql-configured-maria
          mountPath: /docker-entrypoint-initdb.d/create-my-bliss.sql
          subPath: create-my-bliss.sql

      volumes:
      - name: and-sql-configured-maria
        configMap:
          name: and-sky-configured-maria

