db:
  name: "simplydatabase"
  user: "simplymaria"
  host: "at-your-service"
  passwordSecretName: "little-secrets"
  passwordSecretKey: "DB_PASSWORD"

featureDarkMode: "true"

image:
  repository: zulfiaa/ecom-web
  tag: v3
  pullPolicy: IfNotPresent

replicaCount: 1

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu: 50
