apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-pod-for-retail-therapy
spec: # specs for deployment resource
  replicas: 1
  selector:
    matchLabels:
      app: php
  template: # blueprint for pods
    metadata:
      labels:
        app: php
    spec: # specs for web server pod
      containers:
      - name: apache
        image: zulfiaa/ecom-web:v3 # New image with dark mode and banner 
        ports:
        - containerPort: 80

        # Step 2. Adding connection to the database
        env:
        - name: DB_HOST
          value: at-your-service
        - name: DB_NAME
          value: simplydatabase
        - name: DB_USER
          value: simplymaria

        # Step 12. Replacing hardcoded password with a secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: little-secrets
              key: DB_PASSWORD

        # Step 6. Adding a dark mode toggle 
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: and-sky-configured-toggle-and-probes
              key: FEATURE_DARK_MODE

        # Step 11 Adding probes
        livenessProbe:
          httpGet:
            path: /probes/alive-and-kicking.php
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /probes/alive-and-kicking.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5        
        
        volumeMounts:
        - name: probes-volume
          mountPath: /var/www/html/probes

      # Step 11. Add volume for toggle and probes configMap
      volumes:          
      - name: probes-volume
        configMap:
          name: and-sky-configured-toggle-and-probes