apiVersion: v1
kind: Secret
metadata:
  name: little-secrets
type: Opaque
data:
  # echo -n "spillYourBeans" | base64
  DB_PASSWORD: c3BpbGxZb3VyQmVhbnM=
  # echo -n "growYourRoots" | base64
  MYSQL_ROOT_PASSWORD: Z3Jvd1lvdXJSb290cw==