apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-pod-for-maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simply-maria
  template:
    metadata:
      labels:
        app: simply-maria
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.2.20
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: little-secrets
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
#        readinessProbe:
#          exec:
#            command:
#            - mysqladmin
#            - ping
#            - -h
#            - 127.0.0.1
#          initialDelaySeconds: 10
#          periodSeconds: 10
