name: K8s Challenge CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Docker Hub using GitHub PAT
#        run: echo "${{ secrets.DOCKERHUB_PAT }}" 

      - name: Login to Docker Hub using GitHub PAT
        uses: docker/login-action@v3
        with:
          username: zulfiaa
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: zulfiaa/retail-apache:v2
