name: CI/CD Pipelines

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub using GitHub PAT
        run: echo "${{ secrets.DOCKERHUB_PAT }}" 

      - name: Login to Docker Hub using GitHub PAT
        uses: docker/login-action@v2
        with:
          username: zulfiaa
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: zulfiaa/retail-apache:v3

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}


      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/a-pod-for-retail-therapy a-pod-for-retail-therapy=zulfiaa/retail-apache:v3

# [Convert]::ToBase64String([System.IO.File]::ReadAllBytes("C:\Users\zulfi\.kube\config")) > kubeconfig.base64

